### ISSUE TITLE
Sign-up window is truncated in Firefox, rendering signup impossible

### ISSUE THREAD

**Issue by JoKeyser** [Fperdreau/jcm#1]
I'm running Firefox 35.0.1 (on Linux).
Maybe it's just a weird css problem?
![problemsigningupinfirefox](https://cloud.githubusercontent.com/assets/8722846/5941442/562f49ce-a711-11e4-9751-547d722f3856.png)

**Comment by Fperdreau** [comment]
The div "display" property is set to "absolute". This is why it cannot move while scrolling. I tried to set it to "relative", but it does not help. Because this modal window calls on the LeanModal library, I have to look deeper in their code to see how to find a clean solution. However, I found a fix for this issue (although I'm not completely happy with it). Basically, I set the "overflow-y" property of the register form to "scroll". So, now, we can scroll the register form to the end.

**Comment by JoKeyser** [comment]
Yep that works for me, cool!
